### ISSUE TITLE
Suuport for v2?

### ISSUE THREAD

**Issue by chez14** [cristidraghici/Freenom-PHP-Class#2]
Add support for v2 API, i guess?

ref: http://www.freenom.com/en/freenom-api.html

**Comment by cristidraghici** [comment]
Hello,

I haven't taken that into consideration, as I am currently involved in other projects. However, thanks for the heads up and I will take your suggestion into consideration. 

Have a nice day,

Cristi DRAGHICI

**Comment by chez14** [comment]
Thankyou very much, i'll looking forward for it.
