### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by peter279k** [cristidraghici/Freenom-PHP-Class#3]
As title, this project looks good to me. But it has not been maintained for long time.

Is this repository still maintained? If possible, let me be the collaborator and help this repository :+1:.

**Comment by cristidraghici** [comment]
Hello,

I am currently involved with other projects. Unfortunately, this one doesn't receive much attention, at the moment.

So if you want to pitch in with something, the help is always welcome. :)

Thank you. 👍

**Comment by cristidraghici** [comment]
I will close this issue, as I have sent the request to add you as a collaborator. Thanks again :)

**Comment by peter279k** [comment]
@cristidraghici, thank you for your quick reply. I will do my best for this repository :+1:.

I appreciate your invitation.

BTW, can you be the reviewer to review my PRs if possible?

Thanks.
